#pragma once

#include <syclbvh/adaptor/rtcore_config.h>


#define RTC_INVALID_GEOMETRY_ID ((unsigned int)-1)

#if defined(_WIN32) && !defined(__MINGW32__)
#  define RTC_ALIGN(...) __declspec(align(__VA_ARGS__))
#else
#  define RTC_ALIGN(...) __attribute__((aligned(__VA_ARGS__)))
#endif


enum RTCBuildQuality{};
enum RTCFeatureFlags
{
  RTC_FEATURE_FLAG_NONE = 0,

  RTC_FEATURE_FLAG_MOTION_BLUR = 1 << 0,

  RTC_FEATURE_FLAG_TRIANGLE = 1 << 1,
  RTC_FEATURE_FLAG_QUAD = 1 << 2,
  RTC_FEATURE_FLAG_GRID = 1 << 3,

  RTC_FEATURE_FLAG_SUBDIVISION = 1 << 4,

  RTC_FEATURE_FLAG_CONE_LINEAR_CURVE = 1 << 5,
  RTC_FEATURE_FLAG_ROUND_LINEAR_CURVE  = 1 << 6,
  RTC_FEATURE_FLAG_FLAT_LINEAR_CURVE = 1 << 7,

  RTC_FEATURE_FLAG_ROUND_BEZIER_CURVE = 1 << 8,
  RTC_FEATURE_FLAG_FLAT_BEZIER_CURVE = 1 << 9,
  RTC_FEATURE_FLAG_NORMAL_ORIENTED_BEZIER_CURVE = 1 << 10,

  RTC_FEATURE_FLAG_ROUND_BSPLINE_CURVE = 1 << 11,
  RTC_FEATURE_FLAG_FLAT_BSPLINE_CURVE = 1 << 12,
  RTC_FEATURE_FLAG_NORMAL_ORIENTED_BSPLINE_CURVE = 1 << 13,

  RTC_FEATURE_FLAG_ROUND_HERMITE_CURVE = 1 << 14,
  RTC_FEATURE_FLAG_FLAT_HERMITE_CURVE = 1 << 15,
  RTC_FEATURE_FLAG_NORMAL_ORIENTED_HERMITE_CURVE = 1 << 16,

  RTC_FEATURE_FLAG_ROUND_CATMULL_ROM_CURVE = 1 << 17,
  RTC_FEATURE_FLAG_FLAT_CATMULL_ROM_CURVE = 1 << 18,
  RTC_FEATURE_FLAG_NORMAL_ORIENTED_CATMULL_ROM_CURVE = 1 << 19,

  RTC_FEATURE_FLAG_SPHERE_POINT = 1 << 20,
  RTC_FEATURE_FLAG_DISC_POINT = 1 << 21,
  RTC_FEATURE_FLAG_ORIENTED_DISC_POINT = 1 << 22,

  RTC_FEATURE_FLAG_POINT =
    1 << 20  | // RTC_FEATURE_FLAG_SPHERE_POINT |
    1 << 21  | // RTC_FEATURE_FLAG_DISC_POINT |
    1 << 22,   // RTC_FEATURE_FLAG_ORIENTED_DISC_POINT,

  RTC_FEATURE_FLAG_ROUND_CURVES =
    1 << 6  | // RTC_FEATURE_FLAG_ROUND_LINEAR_CURVE |
    1 << 8  | // RTC_FEATURE_FLAG_ROUND_BEZIER_CURVE |
    1 << 11 | // RTC_FEATURE_FLAG_ROUND_BSPLINE_CURVE |
    1 << 14 | // RTC_FEATURE_FLAG_ROUND_HERMITE_CURVE |
    1 << 17,  // RTC_FEATURE_FLAG_ROUND_CATMULL_ROM_CURVE,
  
  RTC_FEATURE_FLAG_FLAT_CURVES =
    1 << 7  | // RTC_FEATURE_FLAG_FLAT_LINEAR_CURVE |
    1 << 9  | // RTC_FEATURE_FLAG_FLAT_BEZIER_CURVE |
    1 << 12 | // RTC_FEATURE_FLAG_FLAT_BSPLINE_CURVE |
    1 << 15 | // RTC_FEATURE_FLAG_FLAT_HERMITE_CURVE |
    1 << 18,  // RTC_FEATURE_FLAG_FLAT_CATMULL_ROM_CURVE,
  
  RTC_FEATURE_FLAG_NORMAL_ORIENTED_CURVES =
    1 << 10 | // RTC_FEATURE_FLAG_NORMAL_ORIENTED_BEZIER_CURVE |
    1 << 13 | // RTC_FEATURE_FLAG_NORMAL_ORIENTED_BSPLINE_CURVE |
    1 << 16 | // RTC_FEATURE_FLAG_NORMAL_ORIENTED_HERMITE_CURVE |
    1 << 19,  // RTC_FEATURE_FLAG_NORMAL_ORIENTED_CATMULL_ROM_CURVE,

  RTC_FEATURE_FLAG_LINEAR_CURVES =
    1 << 5  | // RTC_FEATURE_FLAG_CONE_LINEAR_CURVE |
    1 << 6  | // RTC_FEATURE_FLAG_ROUND_LINEAR_CURVE |
    1 << 7,   // RTC_FEATURE_FLAG_FLAT_LINEAR_CURVE,
  
  RTC_FEATURE_FLAG_BEZIER_CURVES =
    1 << 8  | // RTC_FEATURE_FLAG_ROUND_BEZIER_CURVE |
    1 << 9  | // RTC_FEATURE_FLAG_FLAT_BEZIER_CURVE |
    1 << 10,  // RTC_FEATURE_FLAG_NORMAL_ORIENTED_BEZIER_CURVE,

  RTC_FEATURE_FLAG_BSPLINE_CURVES =
    1 << 11 | // RTC_FEATURE_FLAG_ROUND_BSPLINE_CURVE |
    1 << 12 | // RTC_FEATURE_FLAG_FLAT_BSPLINE_CURVE |
    1 << 13,  // RTC_FEATURE_FLAG_NORMAL_ORIENTED_BSPLINE_CURVE,

  RTC_FEATURE_FLAG_HERMITE_CURVES =
    1 << 14 | // RTC_FEATURE_FLAG_ROUND_HERMITE_CURVE |
    1 << 15 | // RTC_FEATURE_FLAG_FLAT_HERMITE_CURVE |
    1 << 16,  // RTC_FEATURE_FLAG_NORMAL_ORIENTED_HERMITE_CURVE,
  
  RTC_FEATURE_FLAG_CURVES =
    1 << 5  | // RTC_FEATURE_FLAG_CONE_LINEAR_CURVE |
    1 << 6  | // RTC_FEATURE_FLAG_ROUND_LINEAR_CURVE |
    1 << 7  | // RTC_FEATURE_FLAG_FLAT_LINEAR_CURVE |
    1 << 8  | // RTC_FEATURE_FLAG_ROUND_BEZIER_CURVE |
    1 << 9  | // RTC_FEATURE_FLAG_FLAT_BEZIER_CURVE |
    1 << 10 | // RTC_FEATURE_FLAG_NORMAL_ORIENTED_BEZIER_CURVE |
    1 << 11 | // RTC_FEATURE_FLAG_ROUND_BSPLINE_CURVE |
    1 << 12 | // RTC_FEATURE_FLAG_FLAT_BSPLINE_CURVE |
    1 << 13 | // RTC_FEATURE_FLAG_NORMAL_ORIENTED_BSPLINE_CURVE |
    1 << 14 | // RTC_FEATURE_FLAG_ROUND_HERMITE_CURVE |
    1 << 15 | // RTC_FEATURE_FLAG_FLAT_HERMITE_CURVE |
    1 << 16 | // RTC_FEATURE_FLAG_NORMAL_ORIENTED_HERMITE_CURVE |
    1 << 17 | // RTC_FEATURE_FLAG_ROUND_CATMULL_ROM_CURVE |
    1 << 18 | // RTC_FEATURE_FLAG_FLAT_CATMULL_ROM_CURVE |
    1 << 19,  // RTC_FEATURE_FLAG_NORMAL_ORIENTED_CATMULL_ROM_CURVE,

  RTC_FEATURE_FLAG_INSTANCE = 1 << 23,

  RTC_FEATURE_FLAG_FILTER_FUNCTION_IN_ARGUMENTS = 1 << 24,
  RTC_FEATURE_FLAG_FILTER_FUNCTION_IN_GEOMETRY = 1 << 25,

  RTC_FEATURE_FLAG_FILTER_FUNCTION =
    1 << 24 | // RTC_FEATURE_FLAG_FILTER_FUNCTION_IN_ARGUMENTS
    1 << 25,  // RTC_FEATURE_FLAG_FILTER_FUNCTION_IN_GEOMETRY

  RTC_FEATURE_FLAG_USER_GEOMETRY_CALLBACK_IN_ARGUMENTS = 1 << 26,
  RTC_FEATURE_FLAG_USER_GEOMETRY_CALLBACK_IN_GEOMETRY = 1 << 27,

  RTC_FEATURE_FLAG_USER_GEOMETRY =
    1 << 26 | // RTC_FEATURE_FLAG_USER_GEOMETRY_CALLBACK_IN_ARGUMENTS
    1 << 27,  // RTC_FEATURE_FLAG_USER_GEOMETRY_CALLBACK_IN_GEOMETRY

  RTC_FEATURE_FLAG_32_BIT_RAY_MASK = 1 << 28,

  RTC_FEATURE_FLAG_INSTANCE_ARRAY = 1 << 29,

  RTC_FEATURE_FLAG_ALL = 0xffffffff,
};
enum RTCRayQueryFlags{
  /* matching intel_ray_flags_t layout */
  RTC_RAY_QUERY_FLAG_NONE       = 0,
  RTC_RAY_QUERY_FLAG_INVOKE_ARGUMENT_FILTER = (1 << 1), // enable argument filter for each geometry

  /* embree specific flags */
  RTC_RAY_QUERY_FLAG_INCOHERENT = (0 << 16), // optimize for incoherent rays
  RTC_RAY_QUERY_FLAG_COHERENT   = (1 << 16), // optimize for coherent rays
};

struct RTCRayQueryContext{};

inline void rtcInitRayQueryContext(struct RTCRayQueryContext* context){};